#!/usr/bin/env fish

function help_echo
  set_color cyan
  set_color normal
  echo "==========Help Documentation=========="
  set_color green
  echo "argv[1] argv[2+]"
  set_color normal
  echo " -argv[1]:the command to execute"
  echo "  -Available:c(clean cache)
             i(install)
             ir (reinstall)
             p(purge)
             pg(purge with groups,when use it without args,perform an autoremove)
             s(search)
             l(list installed package)
             si(show info of a package)
             sc(source used)
             upd(update database)
             upg(upgrade)
             grab(download and install a package from online repo)
                argv[2]:
                  -Available:
                      upd:update database
                      l:list package in online repo
                      s:search package in online repo
                      xxx:the name of package
                      For example:
                      ctpkg grab l:list package
                      ctpkg grab matcha-gtk-theme:install this package"
  echo " -argv[2+]:the package you want to do on"
  echo "--------------------------------------"
  set_color green
  echo "ctpm argv[2+]"
  set_color normal
  echo " -argv[1]:the command to execute"
  echo "  -Available:
             i(install)
             p(purge)
             l(list installed package)"
  echo " -argv[2+]:the package you want to change"
  echo "========================================"
end

function logger-warn
  set_color magenta
  echo "$prefix [Warn] $argv[1..-1]"
  set_color normal
end
function logger-error
  set_color red
  echo "$prefix [Error] $argv[1..-1]"
  set_color normal
end
function logger-info
  set_color normal
  echo "$prefix [Info] $argv[1..-1]"
  set_color normal
end
function logger-debug
  set_color yellow
  echo "$prefix [Debug] $argv[1..-1]"
  set_color normal
end
function logger-success
  set_color green
  echo "$prefix [Succeeded] $argv[1..-1]"
  set_color normal
end
function logger -d "a lib to print msg quickly"
switch $argv[1]
case 0
  logger-info $argv[2..-1]
case 1
  logger-success $argv[2..-1]
case 2
  logger-debug $argv[2..-1]
case 3
  logger-warn $argv[2..-1]
case 4
  logger-error $argv[2..-1]
end
end

function checkdependence
set 34ylli8_deps_ok 1
for 34ylli8_deps in $argv
    if command -q -v $34ylli8_deps
    else
        set 34ylli8_deps_ok 0
        if test -z "$34ylli8_dep_lost"
            set 34ylli8_deps_lost "$34ylli8_deps $34ylli8_deps_lost"
        else
            set 34ylli8_deps_lost "$34ylli8_deps"
        end
    end
end
if test "$34ylli8_deps_ok" -eq 0
    set_color red
    echo "$prefix [error] "Please install "$34ylli8_deps_lost"to run this program""
    set_color normal
    exit
end
end
function checknetwork
  if curl -s -L $argv[1] | grep -q $argv[2]
  else
    set_color red
    echo "$prefix [error] [checknetwork] check failed - check your network connection"
    set_color normal
  end
end
function dir_exist
  if test -d $argv[1]
  else
    set_color red
    echo "$prefix [error] [checkdir] check failed - dir $argv[1] doesn't exist,going to makr one"
    set_color normal
    mkdir $argv[1]
  end
end
function list_menu
ls $argv | sed '\~//~d'
end

function install_script
set installname $argv[1]
  set dir (pwd)
  set filename (status --current-filename)
  chmod +x $dir/$filename
  sudo cp $dir/$filename /usr/bin/$installname
  set_color green
  echo "$prefix Installed"
  set_color normal
end
function uninstall_script
set installname $argv[1]
  sudo rm /usr/bin/$installname
  set_color green
  echo "$prefix Removed"
  set_color normal
end

function search
    switch $package_manager
        case apt aptitude apk dnf
            $package_manager search $argv
        case pacman
            $package_manager -Ss $argv
        case xbps
            $package_manager-query -Rs $argv
        case '*'
            logger 4 "No support package manager detected"
    end
end

function purge
    switch $package_manager
        case apt
            sudo $package_manager purge $argv
            sudo $package_manager autoremove --purge
        case aptitude
            sudo $package_manager purge $argv
        case pacman
            sudo $package_manager -Rn $argv
            sudo $package_manager -Rn (pacman -Qtdq)
        case apk
            sudo $package_manager del $argv
        case dnf
            sudo $package_manager remove $argv
        case xbps
            sudo $package_manager-remove -R $argv
        case '*'
            logger 4 "No support package manager detected"
    end
end

function grab
    switch $argv[1]
        case upd
            if sudo curl --progress-bar -L -o /var/lib/ctpm/world $ctpm_source/list
                logger 1 "Package List downloaded"
            else
                logger 4 "Failed to download package list from online repo,abort"
                exit
            end
        case upg
            grab upd
            logger 0 "Checking for update"
            if ls -1qA ~/.ctpm/package_info/ | grep -q .
                for ctpm_package in (cd ~/.ctpm/package_info/ && list_menu *.info | sed 's/.info//g')
                    set package_relver (sed -n '/package_relver=/'p ~/.ctpm/package_info/$ctpm_package.info | sed 's/package_relver=//g')
                    set package_relver_repo (sed -n /$ctpm_package=/p /var/lib/ctpm/world | sed s/$ctpm_package=//g)
                    if test $package_relver_repo -gt $package_relver
                        logger 0 "Upgrading $ctpm_package to version:$package_relver_repo"
                        grab $ctpm_package
                    else
                        logger 0 "$ctpm_package is the latest package,skip"
                    end
                end
            end
            if ls -1qA /var/lib/ctpm/package_info/ | grep -q .
                for ctpm_package in (cd /var/lib/ctpm/package_info/ && list_menu *.info | sed 's/.info//g')
                    set package_relver (sed -n '/package_relver=/'p /var/lib/ctpm/package_info/$ctpm_package.info | sed 's/package_relver=//g')
                    set package_relver_repo (sed -n /$ctpm_package=/p /var/lib/ctpm/world | sed s/$ctpm_package=//g)
                    if test $package_relver_repo -gt $package_relver
                        logger 0 "Upgrading $ctpm_package to version:$package_relver_repo"
                        grab $ctpm_package
                    else
                        logger 0 "$ctpm_package is the latest package,skip"
                    end
                end
            end
        case l
            echo "found in source:"
            cat /var/lib/ctpm/world
        case s
            echo "found in source:"
            for ctpm_package in $argv[2..-1]
                grep $ctpm_package /var/lib/ctpm/world
            end
        case '*'
            for ctpm_package in $argv
                logger 0 "Grabbing $ctpm_package"
                if curl --progress-bar -L -o /tmp/$ctpm_package.ctpkg $ctpm_source/$ctpm_package.ctpkg
                    if file /tmp/$ctpm_package.ctpkg | grep -q 'gzip compressed'
                    else
                        logger 4 "The package seems not a ctpkg file,remove and abort,please try to download again and check the package name you typed"
                        rm /tmp/$ctpm_package.ctpkg
                        exit
                    end
                    logger 1 "package:$ctpm_package Downloaded,installing..."
                    cd /tmp
                    extract $ctpm_package.ctpkg
                    rm $ctpm_package.ctpkg
                else
                    logger 4 "package:$ctpm_package failed to download,ignored"
                end
            end
    end
end

function clean
    switch $package_manager
        case apt aptitude
            sudo $package_manager clean $argv
        case pacman
            sudo $package_manager -Scc $argv
        case apk
            logger 4 "No Such function in alpine apk"
        case dnf
            sudo $package_manager clean all $argv
        case xbps
            sudo $package_manager-remove -O $argv
        case '*'
            logger 4 "No support package manager detected"
    end
end

function reinstall
    switch $package_manager
    case apt aptitude
        sudo $package_manager reinstall $argv
    case pacman
        sudo $package_manager -S $argv
    case apk
        sudo $package_manager dev $argv
        sudo $package_manager add $argv
    case dnf
        sudo $package_manager reinstall $argv
    case xbps
        sudo $package_manager-install -f $argv
    case '*'
        logger 4 "No support package manager detected"
end
end
function upgrade
    switch $package_manager
        case apt
            sudo $package_manager update
            sudo $package_manager upgrade $argv
            sudo $package_manager autoremove --purge -y
        case aptitude
            sudo $package_manager update $argv
            sudo $package_manager upgrade $argv
        case pacman
            sudo $package_manager -Syu $argv
        case apk
            sudo $package_manager update $argv
            sudo $package_manager upgrade $argv
        case dnf
            sudo $package_manager update $argv
        case xbps
            sudo $package_manager-install -Su
        case '*'
            logger 4 "No support package manager detected"
    end
end

function show
    switch $package_manager
        case apt aptitude
            $package_manager show $argv
        case pacman
            $package_manager -Si $argv
        case apk dnf
            $package_manager info $argv
        case xbps
            $package_manager-query -RS $argv
        case '*'
            logger 4 "No support package manager detected"
    end
end

function autoremove
    switch $package_manager
        case apt
            sudo $package_manager autoremove --purge $argv
        case aptitude
            sudo $package_manager -o Aptitude::Delete-Unused=1 install $argv
        case pacman
            sudo $package_manager -Rn (pacman -Qtdq) $argv
        case apk
            logger 4 'No Such function in alpine apk'
        case dnf
            sudo $package_manager autoremove $argv
        case xbps
            sudo $package_manager-remove -Oo $argv
        case '*'
            logger 4 "No support package manager detected"
    end
end

function update
    switch $package_manager
        case apt aptitude
            sudo $package_manager update $argv
        case pacman
            sudo $package_manager -Sy $argv
        case apk
            sudo $package_manager update $argv
        case dnf
            sudo $package_manager check-update $argv
        case xbps
            sudo $package_manager-install -S $argv
        case '*'
            logger 4 "No support package manager detected"
    end
end

function source_list
    switch $package_manager
        case apt aptitude
            cat /etc/apt/sources.list | grep --color=never deb
            cat /etc/apt/sources.list.d/* | grep --color=never deb
        case pacman
            cat /etc/pacman.d/mirrorlist | grep --color=never "Server ="
            cat /etc/pacman.conf | grep --color=never "Server =" 
        case apk
            cat /etc/apk/repositories $argv
        case dnf
            $package_manager repolist $argv
        case xbps
            $package_manager-query -L $argv
        case '*'
            logger 4 "No support package manager detected"
    end
end

function list
    switch $package_manager
        case apt aptitude
            apt list --installed $argv
        case pacman
            $package_manager -Qq $argv
        case apk
            $package_manager list $argv
        case dnf
            $package_manager list installed $argv
        case xbps
            $package_manager-query -l $argv
        case '*'
            logger 4 "No support package manager detected"
    end
end

function install
    switch $package_manager
        case apt aptitude
            sudo $package_manager install $argv
        case pacman
            sudo $package_manager -S $argv
        case apk
            sudo $package_manager add $argv
        case dnf
            sudo $package_manager install $argv
        case xbps
            sudo $package_manager-install $argv
        case '*'
            logger 4 "No support package manager detected"
    end
end

function ctconfig_init
    if test -e /etc/centerlinux/conf.d/ctpkg.conf
    else
        set_color red
        echo "$prefix Detected First Launching,We need your password to create the config file"
        set_color normal
        if test -d /etc/centerlinux/conf.d/
        else
            sudo mkdir -p /etc/centerlinux/conf.d/
        end
        echo "source=https://ctpm.ruzhtw.top/" | sudo tee /etc/centerlinux/conf.d/ctpkg.conf &>/dev/null
        echo "backend=" | sudo tee -a /etc/centerlinux/conf.d/ctpkg.conf &>/dev/null
    end
    if test -d /var/lib/ctpm/package_info
    else
        logger 3 'Creating ctpm package info database'
        sudo mkdir -p /var/lib/ctpm/package_info
    end
    if test -d ~/.ctpm/package_info
    else
        logger 3 'Creating ctpm user package info database'
        mkdir -p ~/.ctpm/package_info
    end
end

function detectos
  #debian
  if test -e /etc/debian_version
    if test -e /usr/bin/aptitude
      set -g package_manager aptitude
    else
      set -g package_manager apt
    end
  end
  #archlinux
  if test -e /usr/bin/pacman;and test -e /etc/pacman.d
    set -g package_manager pacman
  end
  #alpine
  if test -e /usr/bin/apk;and test -e /etc/apk
    set -g package_manager apk
  end
  #fedora
  if test -e /etc/fedora-release
    set -g package_manager dnf
  end
  #voidlinux
  if cat /etc/os-release | grep -q 'void';and test -e /usr/bin/xbps-install;
    set -g package_manager xbps
  end
end

function user_list
    if ls -1qA ~/.ctpm/package_info/ | grep -q .
        set_color red
        echo ">Installed-UserLevel<"
        set_color normal
        cd ~/.ctpm/package_info/
        list_menu *.info | sed 's/.info//g'
    else
        set_color red
        echo ">Installed-UserLevel<"
        set_color normal
    end
end

function user_install
    logger 0 "installing $package_name ver:$package_ver pakver:$package_relver as user level"
    cat src/file_list | tee ~/.ctpm/package_info/$package_name >/dev/null
    echo package_name=$package_name | tee ~/.ctpm/package_info/$package_name.info >/dev/null
    echo package_ver=$package_ver | tee -a ~/.ctpm/package_info/$package_name.info >/dev/null
    echo package_relver=$package_relver | tee -a ~/.ctpm/package_info/$package_name.info >/dev/null
    echo package_packager=$package_packager | tee -a ~/.ctpm/package_info/$package_name.info >/dev/null
    echo package_level=$package_level | tee -a ~/.ctpm/package_info/$package_name.info >/dev/null
    echo package_unis=$package_unis | tee -a ~/.ctpm/package_info/$package_name.info >/dev/null
    if [ -s src/unis_hooks ]
        cat src/unis_hooks | tee ~/.ctpm/package_info/$package_name.unis >/dev/null
        chmod +x ~/.ctpm/package_info/$package_name.unis
    end
    for src_file in (cat src/file_list)
        set src_file_dirname (dirname $src_file)
        if test -d $src_file_dirname
        else
            mkdir -p ~/.$src_file_dirname &>/dev/null
        end
        if test -e ~/.$src_file
            rm -rf ~/.$src_file
        end
        mv -f src$src_file ~/.$src_file &>/dev/null
    end
    if [ -s hooks ]
        logger 0 "Running install hooks for $package_name"
        chmod +x hooks
        ./hooks
    end
end

function user_purge
    for package_ctpm in $argv
        set package_unis (sed -n '/package_unis=/'p ~/.ctpm/package_info/$package_ctpm.info | sed 's/package_unis=//g')
        if test -e ~/.ctpm/package_info/$package_ctpm
            for src_file in (cat ~/.ctpm/package_info/$package_ctpm)
                rm -rf ~/$src_file
            end
            if [ "$package_unis" = "1" ]
                if test -e ~/.ctpm/package_info/$package_ctpm.unis
                    ~/.ctpm/package_info/$package_ctpm.unis
                end
            end
            rm ~/.ctpm/package_info/$package_ctpm
            rm ~/.ctpm/package_info/$package_ctpm.info
            if test -e ~/.ctpm/package_info/$package_ctpm.unis
            rm ~/.ctpm/package_info/$package_ctpm.unis
            end
            logger 1 purged package:$package_ctpm
        else
            logger 4 "no info file of package:$package_ctpm,abort"
        end
    end
end

function ctpm_show
    for package_ctpm in $argv[1..-1]
        if test -e /var/lib/ctpm/package_info/$package_ctpm.info
            set package_name (sed -n '/package_name=/'p /var/lib/ctpm/package_info/$package_ctpm.info | sed 's/package_name=//g')
            set package_ver (sed -n '/package_ver=/'p /var/lib/ctpm/package_info/$package_ctpm.info | sed 's/package_ver=//g')
            set package_relver (sed -n '/package_relver=/'p /var/lib/ctpm/package_info/$package_ctpm.info | sed 's/package_relver=//g')
            set package_packager (sed -n '/package_packager=/'p /var/lib/ctpm/package_info/$package_ctpm.info | sed 's/package_packager=//g')
            set package_level (sed -n '/package_level=/'p /var/lib/ctpm/package_info/$package_ctpm.info | sed 's/package_level=//g')
            set package_unis (sed -n '/package_unis=/'p /var/lib/ctpm/package_info/$package_ctpm.info | sed 's/package_unis=//g')
            echo "-----------"
            echo "package name: $package_name"
            echo "package software ver: $package_ver"
            echo "package relver:$package_relver"
            echo "package packager:$package_packager"
            echo "package level: $package_level"
            echo "package unis hook: $package_unis"
            echo "-----------"
        end
        if test -e ~/.ctpm/package_info/$package_ctpm.info
            set package_name (sed -n '/package_name=/'p ~/.ctpm/package_info/$package_ctpm.info | sed 's/package_name=//g')
            set package_ver (sed -n '/package_ver=/'p ~/.ctpm/package_info/$package_ctpm.info | sed 's/package_ver=//g')
            set package_relver (sed -n '/package_relver=/'p ~/.ctpm/package_info/$package_ctpm.info | sed 's/package_relver=//g')
            set package_packager (sed -n '/package_packager=/'p ~/.ctpm/package_info/$package_ctpm.info | sed 's/package_packager=//g')
            set package_level (sed -n '/package_level=/'p ~/.ctpm/package_info/$package_ctpm.info | sed 's/package_level=//g')
            set package_unis (sed -n '/package_unis=/'p ~/.ctpm/package_info/$package_ctpm.info | sed 's/package_unis=//g')
            echo "-----------"
            echo "package name: $package_name"
            echo "package software ver: $package_ver"
            echo "package relver:$package_relver"
            echo "package packager:$package_packager"
            echo "package level: $package_level"
            echo "package unis hook: $package_unis"
            echo "-----------"
        end
    end
end

function extract
    set -lx recudir (pwd)
    set -lx package_ctpm
    if test -d /tmp/ctpm
    else
        mkdir /tmp/ctpm
    end
    if [ -w /tmp/ctpm ]
    else
        logger 4 '/tmp/ctpm is not accessable to this user,abort'
    end
    for package_ctpm in $argv
        if test -e $package_ctpm
        else
            logger 4 "$package_ctpm not found,abort"
            exit
        end
        tar xf $package_ctpm -C /tmp/ctpm
        cd /tmp/ctpm
        logger 0 'Extracted package'
        set -lx package_name (sed -n '/package_name=/'p ctpm_pkg_info | sed 's/package_name=//g')
        set -lx package_ver (sed -n '/package_ver=/'p ctpm_pkg_info | sed 's/package_ver=//g')
        set -lx package_relver (sed -n '/package_relver=/'p ctpm_pkg_info | sed 's/package_relver=//g')
        set -lx package_packager (sed -n '/package_packager=/'p ctpm_pkg_info | sed 's/package_packager=//g')
        set -lx package_level (sed -n '/package_level=/'p ctpm_pkg_info | sed 's/package_level=//g')
        set -lx package_unis (sed -n '/package_unis=/'p ctpm_pkg_info | sed 's/package_unis=//g')
        switch $package_level
            case user
                user_install
            case sys
                sys_install
            case h '*'
                logger 4 "Unknown package level,abort"
                exit
        end
        cd $recudir
        rm -rf ctpm
        logger 0 Processed
    end
end

function sys_install
    logger 0 "installing $package_name ver:$package_ver pakver:$package_relver as sys level"
    cat src/file_list | sudo tee /var/lib/ctpm/package_info/$package_name >/dev/null
    echo package_name=$package_name | sudo tee /var/lib/ctpm/package_info/$package_name.info >/dev/null
    echo package_ver=$package_ver | sudo tee -a /var/lib/ctpm/package_info/$package_name.info >/dev/null
    echo package_relver=$package_relver | sudo tee -a /var/lib/ctpm/package_info/$package_name.info >/dev/null
    echo package_packager=$package_packager | sudo tee -a /var/lib/ctpm/package_info/$package_name.info >/dev/null
    echo package_level=$package_level | sudo tee -a /var/lib/ctpm/package_info/$package_name.info >/dev/null
    echo package_unis=$package_unis | sudo tee -a /var/lib/ctpm/package_info/$package_name.info >/dev/null
    if [ -s src/unis_hooks ]
        cat src/unis_hooks | sudo tee /var/lib/ctpm/package_info/$package_name.unis >/dev/null
        sudo chmod +x /var/lib/ctpm/package_info/$package_name.unis
    end
    for src_file in (cat src/file_list)
        set src_file_dirname (dirname $src_file)
        if test -d "$src_file_dirname"
        else
            sudo mkdir "$src_file_dirname" &>/dev/null
        end
        if test -e $src_file
            sudo rm -rf $src_file
        end
        sudo mv -f src$src_file $src_file &>/dev/null
    end
    if [ -s hooks ]
        logger 0 "Running install hooks for $package_name"
        sudo chmod +x hooks
        sudo ./hooks
    end
end

function sys_list
    if ls -1qA /var/lib/ctpm/package_info/ | grep -q .
        set_color red
        echo ">Installed-SysLevel<"
        set_color normal
        cd /var/lib/ctpm/package_info/
        list_menu *.info | sed 's/.info//g'
    else
        set_color red
        echo ">Installed-SysLevel<"
        set_color normal
    end
end

function sys_purge
    for package_ctpm in $argv
        set package_unis (sed -n '/package_unis=/'p /var/lib/ctpm/package_info/$package_ctpm.info | sed 's/package_unis=//g')
        if test -e /var/lib/ctpm/package_info/$package_ctpm
            for src_file in (cat /var/lib/ctpm/package_info/$package_ctpm)
                sudo rm -rf $src_file
            end
            if [ "$package_unis" = 1 ]
                if test -e /var/lib/ctpm/package_info/$package_ctpm.unis
                    sudo /var/lib/ctpm/package_info/$package_ctpm.unis
                end
            end
            sudo rm /var/lib/ctpm/package_info/$package_ctpm
            sudo rm /var/lib/ctpm/package_info/$package_ctpm.info
            if test -d /var/lib/ctpm/package_info/$package_ctpm.unis
                sudo rm /var/lib/ctpm/package_info/$package_ctpm.unis
            end
            logger 1 purged package:$package_ctpm
        else
            logger 4 "no info file of package:$package_ctpm,abort"
        end
    end
end

echo Build_Time_UTC=2022-03-30_03:32:57
set -lx prefix [ctpkg]
checkdependence file curl tar rm mv
ctconfig_init
set -lx ctpm_source (sed -n '/source=/'p /etc/centerlinux/conf.d/ctpkg.conf | sed 's/source=//g')
set -g package_manager (sed -n '/backend=/'p /etc/centerlinux/conf.d/ctpkg.conf | sed 's/backend=//g')
if [ "$ctpm_source" = "" ]
    set ctpm_source https://ctpm.ruzhtw.top/
end
if [ "$package_manager" = "" ]
    detectos
end
argparse -i -n $prefix 's/ctsource=' 'b/ctbackend=' -- $argv
if set -q _flag_ctbackend
    set -g package_manager $_flag_ctbackend
end
if set -q _flag_ctsource
    set ctpm_source $_flag_ctsource
end
logger 0 "Set backend as $package_manager"
switch $argv[1]
    case c
        clean $argv[2..-1]
    case grab
        logger 0 "Set backend as ctpm"
        logger 0 "Using ctpm source:$ctpm_source"
        grab $argv[2..-1]
    case i
        install $argv[2..-1]
    case ir
        reinstall $argv[2..-1]
    case p
        purge $argv[2..-1]
    case pg
        autoremove $argv[2..-1]
    case s
        search $argv[2..-1]
    case l
        list $argv[2..-1]
    case si
        show $argv[2..-1]
    case sc
        source_list $argv[2..-1]
    case upd
        update $argv[2..-1]
    case upg
        upgrade $argv[2..-1]
    case ctpm
        switch $argv[2]
            case i
                extract $argv[3..-1]
            case l
                switch $argv[3]
                    case sys
                        sys_list
                    case user
                        user_list
                    case '*'
                        sys_list
                        user_list
                end
            case p
                switch $argv[3]
                    case sys
                        sys_purge $argv[4..-1]
                    case user
                        user_purge $argv[4..-1]
                    case h help '*'
                        help_echo
                end
            case ss
                ctpm_show $argv[3..-1]
            case h help '*'
                help_echo
        end
    case install
        install_script ctpkg
    case uninstall
        uninstall_script ctpkg
    case v version
        logger 0 "CenterLinux Package Manager Version Corleone@build1 | TeaHouseLab at ruzhtw.top"
    case h help '*'
        help_echo
end
set -e package_manager